// Project: SandboxGPUs.
// Author: Ashot Vardanian.
// Created: 04/09/2019.
// Copyright: Check "License" file.
//

#version 450

layout(std430, binding = 0) buffer lay0 { float xA[]; };
layout(std430, binding = 1) buffer lay1 { float xB[]; };
layout(std430, binding = 2) buffer lay2 { float y[]; };

/// gArithmAddArr();
void main() {
    uint const lId = gl_GlobalInvocationID.x;
    y[lId] = xA[lId] + xB[lId];
}
