// Project: SandboxGPUs.
// Author: Ashot Vardanian.
// Created: 04/09/2019.
// Copyright: Check "License" file.
//

#version 450

layout(std430, binding = 0) buffer lay0 { vec4 xA[]; };
layout(std430, binding = 1) buffer lay1 { vec4 xB[]; };
layout(std430, binding = 2) buffer lay2 { vec4 y[]; };

/// gArithmMulConst4();
void main() {
    uint const lId = gl_GlobalInvocationID.x;
    y[lId] = xA[lId] * xB[lId];
}
